# Generated by Django 5.2.7 on 2025-10-17 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_upload', '0002_uploadedfile_extracted_text_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.uploadedfile')),
            ],
        ),
    ]
