# Generated by Django 5.2.7 on 2025-10-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatednote',
            old_name='note',
            new_name='notes',
        ),
    ]
