# Generated by Django 5.2.7 on 2025-10-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_notes', '0002_rename_note_generatednote_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatednote',
            old_name='created_at',
            new_name='generated_at',
        ),
    ]
